### ISSUE TITLE
Currency & Ticket System

### ISSUE THREAD

**Issue by crnbezuidenhout** [johnnyq/itflow#275]
Awesome application/site btw...
I have downloaded the files and started playing around... one powerful application. 

I have noticed that when sending a invoice/quote via mail, the currency symbol stays as $ and not via the currency selected.
Also when creating tickets, the response or email does not get sent to the client.

**Comment by wrongecho** [comment]
Welcome @crnbezuidenhout!
We're still in beta with the application at the moment so a lot of features are still in development or may have bugs. 
In terms of the e-mail currency not showing for quotes/invoices, I've just submitted a pull request to fix that, nice catch.
We still need to implement e-mail functionality in tickets. Outgoing emails should be relatively simple but processing replies is likely going to be more of a challenge and might be beyond the 1.0 release. We're also aiming to have a public frontend for the ticket system too eventually, I think.
If you come across any more bugs, feel free to raise an issue. Can't guarantee they'll be fixed right away but all feedback is appreciated! :)

**Comment by crnbezuidenhout** [comment]
Thanks Johnnyq/Itflow

I will play around and will keep you posted should I find something.

Again this is a super awesome idea and I love the fact that it's invoplving
the community.

I have noticed the following so far:
- within tickets, its keeps showing "Needs Approval" on the right hand side
- The Invoice button does not do anything ( not a big deal as its still
beta )
- When a mail is sent, it states that the mail was sent however does not
refresh the page back to the invoices page, one has to go back manually

Thanks for the quick update and fix

Enjoy...

**Comment by wrongecho** [comment]
I totally agree - I love the fact that this application is open source. It has such potential! 
On that note, if you find anything that you can fix yourself (even if it's just a typo, etc), feel free to submit a pull request. I'm sure Johnny appreciates all the help he can get.

I know that the "Needs approval" & Invoice button in ticketing was only recently added. I think the option is for break/fix hourly-billed clients so that if someone is not a primary/approved contact, work can't be done/invoiced until it's approved? Not entirely sure as it seems to say needs approval for all client contacts at the moment, (and as you say the invoice button is just a placeholder currently) but I'm sure they'll take shape over time.

Most form submissions will take you to the page you were on when you performed the action. Assuming this is working, do you mean that it doesn't go back to the main invoices page (/invoices.php) page? If so, I can see the appeal there. You've sent the invoice, you're done with that one, back to the main page to send another - kinda thought process?

**Comment by crnbezuidenhout** [comment]
_

> "Most form submissions will take you to the page you were on when you performed the action. Assuming this is working, do you mean that it doesn't go back to the main invoices page (/invoices.php) page? If so, I can see the appeal there. You've sent the invoice, you're done with that one, back to the main page to send another - kinda thought process?"

_

Yes so basically redirecting you back to the invoice\quote page where once dos not have to manually go back...

So from "post.php?email_invoice=8" it then gets redirected to "invoices.php"... after as second or 2... same with quotes and the rest...

I only have basic knowledge when it comes to these type of stuff, so will try my best to assist where possible...

how does one then make changes from a pull request if you don't mind me asking :D ...

**Comment by johnnyq** [comment]
Added Currency Symbol in a few more places

f8e9c2ee5dbe44ed66ce0faca3b8f063b0dff673

**Comment by johnnyq** [comment]
Thank you for your feed back @crnbezuidenhout 
You can help in many other ways besides code commits
here are a few ways to help:

- Report bugs, feature (keep it one bug one feature per github issue)
- UI/UX Suggestions improvement (Wiremaps, diagrams, flow etc)
- Documentation (This can be added to itflows website
- Youtube Videos
- Getting the word out there.
- All helps

**Comment by wrongecho** [comment]
@crnbezuidenhout 
> Yes so basically redirecting you back to the invoice\quote page where once dos not have to manually go back...
> So from "post.php?email_invoice=8" it then gets redirected to "invoices.php"... after as second or 2... same with quotes and the rest...

I agree, it makes more sense to send you to the main quote/invoice page after sending the e-mail rather than back to that specific invoice/quote...I'll add it to my list.

As Johnny said, there are other ways to contribute without coding... But if you are interested in learning a bit more about the code side of things, feel free to take a look at [this](https://www.dataschool.io/how-to-contribute-on-github/) tutorial.

Thanks again :)

**Comment by crnbezuidenhout** [comment]
> Added Currency Symbol in a few more places
> 
> [f8e9c2e](https://github.com/johnnyq/itflow/commit/f8e9c2ee5dbe44ed66ce0faca3b8f063b0dff673)

Hi, did another test and balance due still reflects the $ currency and not the country selected... please see below
![image](https://user-images.githubusercontent.com/97749452/149987742-c171f137-26ba-4bd2-86b9-543a830dd651.png)

**Comment by wrongecho** [comment]
Can't seem to replicate this. Have you updated since the changes were made?

**Comment by johnnyq** [comment]
closing cant replicate either
