### ISSUE TITLE
On New Ticket: Add the asset field

### ISSUE THREAD

**Issue by Wikiphil** [johnnyq/itflow#302]
Can we add the Asset field in the ticket open windows?

![new-ticket](https://user-images.githubusercontent.com/84292480/150188411-d5d2007f-b9d0-440d-bc25-294a73ac9e53.png)

We have to open the ticket to choose the asset after creation

![edit-ticket](https://user-images.githubusercontent.com/84292480/150188612-7cfabbec-dc19-4c5e-866f-e2b0e6d3da5d.png)

**Comment by Wikiphil** [comment]
When you already are in a Client! :-) From the main screen, it's a bit harder to list all assets.

**Comment by wrongecho** [comment]
The reason this wasn't added on the ticket creation popup / modal is because the popup then becomes too big with the extra line. The ticket edit has the ticket assigned to box removed on the edit view, so that makes room for it.

We could definitely add it, but it means you then have to scroll a bit for most screens. Open to this, see what Johnny thinks? 

Also, I want to add support for multiple assets and maybe suggest assets that are assigned to the ticket contact.. Eventually..

**Comment by Wikiphil** [comment]
I Understand, Client is already switched by Contact depand on "New Ticket" location.

**Comment by wrongecho** [comment]
Added this via #307.
