### ISSUE TITLE
Technician role can change Global Admin passwords

### ISSUE THREAD

**Issue by Superfish1000** [johnnyq/itflow#361]
I have been loving what im seeing so far, but i just realized that the technician role can change Global Admin passwords.

This is a serious issue and considering this behavior coupled with the lack of permissions checking on pages mentioned in issue #321, I imagine it is possible for clients to also change global admin passwords.

**Comment by wrongecho** [comment]
Hi @Superfish1000, and welcome! 

Thanks for pointing this out. My view is that ITFlow is currently in beta, shouldn't be used to store sensitive info and you shouldn't grant access to untrusted users at this time. It's a huge work in progress, and we're getting there slowly. 

I think eventually we'll move client access to a separate part of the site with a separate login/auth system. This just does away with all this risk, etc.

We can look at evaluating tech access levels against the user they are resetting the password for but I can see a genuine use case for resetting the global admin password from a tech account - maybe they genuinely forgot it? Or say you're a small company and your global admin just quits one day, what happens then? 
Note that since the encrypted logins (for assets) in ITFlow in part use the user account password, a password has to be set from someone with an account already. Self service password reset is not possible. 
It was either this, or to leave the logins encryption key in plain text in the database. 

I definitely think some alerting for password resets would be helpful (maybe an email notification?).

Would love to hear your thoughts! :)

**Comment by Superfish1000** [comment]
I would say that there is no valid use case for a tech to change the global admin password.  There should be another recovery method implemented to allow a reset in the event of the the examples you gave.
Minimally, the global admin password should currently be changeable by manually editing the SQL database.

If a technician is not limited in changing the global admin password then there is zero reason to even have these roles.

This alone would mean I would never use this in production.

**Comment by wrongecho** [comment]
Nothing here is set in stone as far as I'm aware. These are all valid concerns, we just need to find the best approach.

A little about the setup currently:
**User/Tech passwords to login to ITFlow**
User/tech passwords are hashed and salted using [password_hash](https://www.php.net/manual/en/function.password-hash.php). 
This means we don't ever actually know the password, we just verify it against the hash. As far as I'm aware, this is best practice.

**Asset Passwords**
Asset passwords/Logins are encrypted using an AES key. 
Previously this key was stored plaintext, but this isn't great as all an attacker has to do is dump the database and they are able to decrypt any logins. I raised #264 regarding this and made some changes based on [this ](https://security.stackexchange.com/questions/12332/where-to-store-a-server-side-encryption-key/12334#12334)stackover flow post. I went with an adapted version of option 3 - "Tie the encryption key to your admin login".
What happens now is that the AES key is generated but then stored in an encrypted form with the user's password as the cipher text. This happens for all users. The only downside is that users passwords must be created/set from a session that has access to the AES key - I explain it a bit better [here](https://github.com/johnnyq/itflow/issues/264#issuecomment-1010458209) and [here](https://github.com/johnnyq/itflow/pull/265).

> There should be another recovery method implemented to allow a reset in the event of the the examples you gave. Minimally, the global admin password should currently be changeable by manually editing the SQL database.

So perhaps the solution would be that anyone using ITFlow has at least two global admins, and only global admins can reset tech's passwords? You could indeed manually generate the user hash / encrypted AES key and edit SQL directly, it's just not very user friendly. We could possibly make a utility for this.

> Additionally, why would the password ever need to be unencrypted to perform a self service password reset? All that should be required is a verification email to the user.

Think of something like Keypass or BitWarden - if you forget your master key, they can't help you. This is because the master key (in this case the users ITFlow login) is used to encrypt the key that encrypts the data. It's a trade off between security and usability. Quite frankly, I'd prefer to lose access to client's passwords than an attacker successfully gain access them.

> Now that I have brought these issues up I would like to say that I am loving what you guys put together so far and it looks really promising. If I were to look into fixing some of the bugs I find would you guys be open to the pull requests?

By all means! All help is appreciated. I know Johnny was looking into #321 but he is incredibly busy so I'm sure he'd appreciate the help. This project is almost pure PHP and quite simple overall! My only advice would be try and gain a bit of consensus before you change something too drastically. This just helps save everyone time :)

If you have any questions or issues, I am more than happy to help out where possible.

**Comment by Superfish1000** [comment]
> Think of something like Keypass or BitWarden - if you forget your master key, they can't help you. This is because the master key (in this case the users ITFlow login) is used to encrypt the key that encrypts the data. It's a trade off between security and usability. Quite frankly, I'd prefer to lose access to client's passwords than an attacker successfully gain access them.

I think I'm starting to understand the issue now given some of the notes you made earlier in this reply.  Am I correct that certain functions of the site are tied to the hashed password of the global admin?  If so I think this is a bad approach unless the intention is to never use the global admin password.  I would instead suggest generating a private key at initialization of the database that is then used for this function.  As you said, an attacker could dump the database, so it may not be best to store this key in the database itself but externally.  Would need to think about it and I don't have time atm.

> By all means! All help is appreciated. I know Johnny was looking into #321 but he is incredibly busy so I'm sure he'd appreciate the help. This project is almost pure PHP and quite simple overall! My only advice would be try and gain a bit of consensus before you change something too drastically. This just helps save everyone time :)
> 
> If you have any questions or issues, I am more than happy to help out where possible.

I'm glad to hear this and will absolutely let you know if I have questions.  I'm sure it'll take me a bit to get a handle on how everything is set up.

**Comment by wrongecho** [comment]
> I think I'm starting to understand the issue now given some of the notes you made earlier in this reply. Am I correct that certain functions of the site are tied to the hashed password of the global admin? If so I think this is a bad approach unless the intention is to never use the global admin password. I would instead suggest generating a private key at initialization of the database that is then used for this function. As you said, an attacker could dump the database, so it may not be best to store this key in the database itself but externally. Would need to think about it and I don't have time atm.

Tied to tech account passwords in general, not just the global admin. Essentially a shared key, but encrypted with each users password.

In [setup](https://github.com/johnnyq/itflow/blob/master/setup.php#L402), we generate an initial encryption key and a user "session" key (which is the AES encryption key encrypted with the user's account password). (See also: [functions.php](https://github.com/johnnyq/itflow/blob/master/functions.php))

```
//Generate master encryption key
$site_encryption_master_key = keygen();

//Generate user specific key
$user_specific_encryption_ciphertext = setupFirstUserSpecificKey($_POST['password'], $site_encryption_master_key);

mysqli_query($mysqli,"INSERT INTO users SET user_name = '$name', user_email = '$email', user_password = '$password', user_specific_encryption_ciphertext = '$user_specific_encryption_ciphertext', user_created_at = NOW()");
```

Whenever the user [logins in](https://github.com/johnnyq/itflow/blob/master/login.php#L72), their password is used to decrypt the AES key and set it in their session
```
// Setup encryption session key
if (isset($row['user_specific_encryption_ciphertext'])) {
    $user_encryption_ciphertext = $row['user_specific_encryption_ciphertext'];
    $site_encryption_master_key = decryptUserSpecificKey($user_encryption_ciphertext, $password);
    generateUserSessionKey($site_encryption_master_key);
}
```

Whenever a user retrieves a password entry, it is [decrypted](https://github.com/johnnyq/itflow/blob/master/client_assets.php#L268) using the AES key in their session. 
```
$login_password = decryptLoginEntry($row['login_password']);
```

When a [new user is added](https://github.com/johnnyq/itflow/blob/master/post.php#L57) (from an admin account that has the encryption key in their session), a user-specific encryption ciphertext is set. This allows them to decrypt logins.
```
$user_specific_encryption_ciphertext = encryptUserSpecificKey($_POST['password']);
[...]
mysqli_query($mysqli,"INSERT INTO users SET user_name = '$name', user_email = '$email', user_password = '$password', user_specific_encryption_ciphertext = '$user_specific_encryption_ciphertext', user_created_at = NOW()");
```

If/When a user [updates](https://github.com/johnnyq/itflow/blob/master/post.php#L191) their password, the user-specific encryption ciphertext is updated:
```
if(!empty($new_password)){
    $new_password = password_hash($new_password, PASSWORD_DEFAULT);
    $user_specific_encryption_ciphertext = encryptUserSpecificKey($_POST['new_password']);
    mysqli_query($mysqli,"UPDATE users SET user_password = '$new_password', user_specific_encryption_ciphertext = '$user_specific_encryption_ciphertext' WHERE user_id = $user_id");
    //Extended Logging
    $extended_log_description .= ", password changed";
}
```

Let me know if you have any questions/suggestions on how this is set up. This is the best way I could think of that allows multiple users access to passwords with no manually shared secret between them.

> I'm glad to hear this and will absolutely let you know if I have questions. I'm sure it'll take me a bit to get a handle on how everything is set up.

Great! Please let me know :)

**Comment by Superfish1000** [comment]
> Tied to tech account passwords in general, not just the global admin. Essentially a shared key, but encrypted with each users password.
> 
> In [setup](https://github.com/johnnyq/itflow/blob/master/setup.php#L402), we generate an initial encryption key and a user "session" key (which is the AES encryption key encrypted with the user's account password). (See also: [functions.php](https://github.com/johnnyq/itflow/blob/master/functions.php))

Admittedly not an expert in encryption, but the idea of having the same key stored in every user account, all be it with a different encryption phrase, makes me uncomfortable.  Just thinking back to the WEP days when just capturing enough of your neighbors wifi traffic would allow you to reverse engineer his password.  Maybe I'm just paranoid...

I go to look it up and come to find that you can have a different key for each user, but it is doing basically what you described on the back end. lol
https://stackoverflow.com/questions/597188/encryption-decryption-with-multiple-keys

**Comment by wrongecho** [comment]
Not a cryptography expert by any means but I think the issue with WEP was the reuse of the IV. We generate a new IV and Salt for each encrypted credential. 

https://github.com/johnnyq/itflow/blob/master/functions.php#L384-L389

Whether encrypting the same key for each user is an issue is debated, but doesn't seem to be much of an issue. 
It's the only way I could think of to implement shared encryption without using something like a TPM (but I don't think most people are going to have one as part of VPS hosting?) 
I'm happy to be corrected and for any changes to this. But yeah, its very close to that post.

Just out of interest, how did you come across ITFlow? :)

**Comment by johnnyq** [comment]
@Superfish1000 As @wrongecho has stated, this is best practice on handling passwords as this is the same way big Password managers handle their passwords for example Bitwarden. We have made this decision together and we both agree this is the best route. In the future we may implement TPM or hardware key like Yubikey decryption in the future.

We do want to thank you for your interest in ITFlow and bringing up your concern regarding the way logins are encrypted in the database. Very few people bring up concerns and questions regarding security, and that's how things slip by. We very much appreciate you for this.

 @wrongecho had a discussion with me and he has decided to take it upon himself to give a write up on how the encryption works on our Documents page, just so its clear.

**Comment by Superfish1000** [comment]
> @Superfish1000 As @wrongecho has stated, this is best practice on handling passwords as this is the same way big Password managers handle their passwords for example Bitwarden. We have made this decision together and we both agree this is the best route. In the future we may implement TPM or hardware key like "Yubikey" decryption.
> 
I honestly had no idea that's how that was handled.  I came to the same conclusion though after reading the explanation of how GPG handles it that I linked.

> We do want to thank you for your interest in ITFlow and bringing up your concern regarding the way logins are encrypted in the database. Very few people bring up concerns and questions regarding security, and that's how things slip by. We very much appreciate you for this. 
> 

Absolutely.  I just hope I didn't come off too abrasive.

@wrongecho I found ITFlow because I was looking for an open source alternative to ITGlue, I believe it was ITG at the time..., and stumbled upon a post on the Lawrence Systems forum.

So far I'm really impressed and excited to see this project progress.

**Comment by wrongecho** [comment]
Hello again!

I'm glad you're as excited about ITFlow as we are. Things are slowly coming together!

I have written up a high-level overview of how the login encryption process works on the [docs](https://itflow.org/docs.php?doc=logins) and linked to the relevant PR.

Whilst still a work in progress, ITFlow user roles have been changed - now there is just Admin/Tech/Accountant. We've put together an access matrix and will be implementing it at some point (both in the UI & in the code). 

Please feel free to raise further issues here or suggestions on the [forum](https://forum.itflow.org/)!

**Comment by wrongecho** [comment]
We will address this alongside the access matrix enforcement mentioned in #321.
