### ISSUE TITLE
Installation Documentation needs an update

### ISSUE THREAD

**Issue by sohgnar** [johnnyq/itflow#388]
Using the latest installer for ubuntu server and following the guide the following issues were noted:

Ubuntu installs PHP7.4 by default. (I had to update this to 8.0 as the guide references 8.0 and I encountered an error following the guide)
Guide doesn't account for installing or enabling mysqli in php. So after creating the database and downloading the git repo I received an http500 error and errors in the apache log after entering the database details in the setup page.

**Comment by wrongecho** [comment]
Hey @sohgnar.

Thanks for getting in touch! :)

As discussed in Discord, I modeled the instructions on 21.10 (which installs PHP 8) rather than the latest LTS 20.04.

I've updated the [docs](https://itflow.org/docs.php?doc=installation) to reflect PHP 7.4 being installed by default and that php-mysqli is required to interact with MariaDB.

Please let me know if I've missed anything else!

**Comment by sohgnar** [comment]
Thanks for being so prompt!
